version: "2"

checks:
    method-complexity:
        config:
            threshold: 9

exclude_patterns:
    - "**/tests/"
    - "**/vendor/"

plugins:
    phpcodesniffer:
        enabled: true
        config:
            standard: "PSR12"
